### ISSUE TITLE
Bomb does a weird dash, making it very inconsistent to hit the dynamite

### ISSUE THREAD

**Issue by BunnyBride** [Moffein/BanditDynamite#4]
Basically what it says. Not sure if intentional or not.
Clicking on M2 launches the bomb but also does a weird dash, which is cool in itself but it is too "wonky" and it's impossible to hit the dynamite well.

**Comment by Moffein** [comment]
Looked into the issue, and unfortunately I'm unsure of what the cause is.
The SotS update broke a lot of stuff, and unfortunately I probably won't have the time to get around to fully troubleshooting this, so I'll deprecate the mod and see if there's anyone in the modding discord willing to continue maintaining it.
